# Generated by Django 4.2 on 2025-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to="face_images/"),
        ),
    ]
