# Generated by Django 4.2 on 2025-11-03 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "employee"]},
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-applied_on"]},
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("emergency", "Emergency Leave"),
                    ("vacation", "Vacation"),
                ],
                default="casual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="reviewed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
